# Generated by Django 6.0 on 2025-12-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
